### ISSUE TITLE
Filter tasks by external:data custom fields

### ISSUE THREAD

**Issue by dbaltas** [Asana/asana-api-meta#37]
It is great that asana api provides a [way](https://asana.com/developers/documentation/getting-started/custom-external-data) to save custom data.

Currently the `external:data` field allows storage of string characters.
It would be great if json objects can be stored so that when I update a task with the following external data
```json
          external: {
            "id": 1234567899,
            "data": "{ 'time_estimate': 3600, 'time_spent': 1482 }"
          }
```

I can then filter tasks that match for example the custom field `time_estimate`
```javascript
client.tasks.findByExternalField({'time_estimate': 3600})
//or
client.tasks.findBy({'external:time_estimate': 3600})
```

returning a list of tasks

**Comment by marcogallotta** [comment]
Thanks for your suggestion! We have a much more comprehensive feature coming soon, that will warrant this unnecessary. Closing this out.
